### ISSUE TITLE
Powershell overload error creating pdf reader using byte array as parameter

### ISSUE THREAD

**Issue by Salva-G** [itext/itextsharp#13]
Hi
I have an error trying to create a pdf reader using byte array as parameter.  Posted all details at http://stackoverflow.com/q/37072644/5927274

Thanks

**Comment by amedee** [comment]
Hi! Thanks for your message. We prefer to use StackOverflow for technical support and reserve GitHub for bug reports and pull requests. There is already an answer on StackOverflow, so I will close your question here.
