### ISSUE TITLE
Issue in MakeSignature.SignDetached method

### ISSUE THREAD

**Issue by MADzO** [itext/itextsharp#15]
Hi,
I`m having a problem using the method MakeSignature.SignDetached. I managed to locate the problem in virtual public PdfObject GetFileID(bool modified) which is implemented in PdfEncryption.cs.
The method was passing null documentID to the CreateInfoId method. In CreateInfoId the code is :
```
if(id.Length == 0)
    id = CreateDocumentId();
```
and when id is null I`m getting null object reference.
So to fix you should check:

`if (id == null || id.Length == 0).`

To reproduce the issue you should try to sign pdf which is encrypted with certificate.

Best regards,
Jovica

**Comment by amedee** [comment]
Hi! Could you make this into a pull request? Please read our Contributing Guide for more details: https://github.com/itext/itextsharp/blob/master/CONTRIBUTING.md

**Comment by amedee** [comment]
See #16 for pull request.
