### ISSUE TITLE
Text not showing when downloading from iPhone

### ISSUE THREAD

**Issue by pauldunstone** [itext/itextsharp#19]
Hi there

Might just be something I am doing wrong but my PDF works when downloading from desktop but on my mobile devices the images show but the text doesn't. Here is my generation code:

            Response.ClearContent();
            Response.ClearHeaders();
            Response.ContentType = "application/pdf";
            Response.Buffer = true;
            Response.AppendHeader("Accept-Header", memoryStream.GetBuffer().Length.ToString());
            Response.AppendHeader("content-disposition", "attachment; filename=\"" + HttpUtility.UrlEncode(filename, System.Text.Encoding.UTF8) + "\"");
            Response.AppendHeader("Pragma", "public");
            Response.BinaryWrite((byte[])memoryStream.ToArray());
            Response.Flush();
            Response.End();

I am using Times Roman Bold as my font.

Has anyone else come across this before?

Regards, Paul

**Comment by amedee** [comment]
Hello, 
We use GitHub only for bug reports and pull requests.
For community support, please ask your question on StackOverflow: http://stackoverflow.com/questions/tagged/itextsharp 
If you are a customer with a support contract, you have access to the iText JIRA. 

For more information, please see http://itextpdf.com/support
