### ISSUE TITLE
Problem with unicode display

### ISSUE THREAD

**Issue by haraman21** [itext/itextsharp#3]
Hi
When exporting from asp.net to PDF using PANJABI (PN) as language the library exports certain characters improperly particularly ( ਿ) character such as:
ਕਿਰ੍ਪਾ       is displayed as    ਕ੍ਰਿਪਾ
ਵਿਦਿਆਰਥੀ    is displayed as       ਵ ਿਦ ਿਆਰਥੀ   (without spaces before and after  ਿ)

One important thing to note is that when we copy the entire text from generated pdf to any other text editor such as Notepad or in any browser the characters / words are automatically corrected there.

Platform:
Development environment: Visual Studio 2010
Language: VB
iTextSharp version: tested with 4.1.2 and 5.4.2
Tested with: HTML Parser in 4.1.2 and XML Worker in 5.4.2
OS: Windows XP, Windows 7, Windows Server 2008

**Comment by amedee** [comment]
For Professional Support, please see http://itextpdf.com/support
For Community Support, please ask your question on StackOverflow: http://stackoverflow.com/questions/tagged/itextsharp
