### ISSUE TITLE
Error converting html to pdf/a

### ISSUE THREAD

**Issue by fabiohvp** [itext/itextsharp#4]
Hi, I'm having problems when converting Html to pdf/a.

When using PdfWriter the conversion is OK, but when using PdfAWriter, if my html has unordered lists, <ol><ul>.. or big tables <table>, the generated pdf will only work until the first occurrence of one of these elements and then it will be blank. 

I'm posting the code I'm using, an example of html and will attach the pdf file.

Code:
 public static byte[] Convert(string html)
        {
            MemoryStream ms = new MemoryStream();
            Document document = new iTextSharp.text.Document(PageSize.A4);
            PdfAWriter writer = PdfAWriter.GetInstance(document, ms, PdfAConformanceLevel.PDF_A_1B);
            //PdfWriter writer = PdfWriter.GetInstance(document, ms);
            writer.PdfVersion = PdfWriter.VERSION_1_7;
            writer.SetTagged();
            writer.ViewerPreferences = PdfWriter.DisplayDocTitle;
            writer.CloseStream = false;
            writer.InitialLeading = 12.5f;
            writer.CompressionLevel = PdfStream.BEST_COMPRESSION;

            try
            {
                document.AddLanguage("pt-BR");
                document.AddCreationDate();
                writer.CreateXmpMetadata();
                document.Open();
                ICC_Profile icc = ICC_Profile.GetInstance((byte[])Properties.Mensagens.ResourceManager.GetObject("icc_profile"));
                writer.SetOutputIntents("Custom", "", "http://www.color.org", "sRGB IEC61966-2.1", icc);

                MemoryStream cssStream = new MemoryStream(Encoding.UTF8.GetBytes("html, html * { font-family: Arial, Arial, Arial!important; color: black!important; }"));
                MemoryStream htmlStream = new MemoryStream(Encoding.UTF8.GetBytes(html));
                XMLWorkerHelper.GetInstance().ParseXHtml(writer, document, htmlStream, cssStream);
                document.Close();
                writer.Close();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            byte[] byteArray = ms.ToArray();
            ms.Close();

            return byteArray;
        }

I put an picture of the html together because the html in here is displaying unformatted.
Thanks for your help in advance.

![testexample pdf - adobe reader](https://cloud.githubusercontent.com/assets/8272995/4651237/5f90f8ba-549a-11e4-9922-f69903ff996b.jpg)

**Comment by amedee** [comment]
For Professional Support, please see http://itextpdf.com/support
For Community Support, please ask your question on StackOverflow: http://stackoverflow.com/questions/tagged/itextsharp
